### PR TITLE
Change feed URLs and API key parameter to switch to api.mta.info.

### PR DESCRIPTION
**Pull request by kurtraschke**
`datamine.mta.info` has been replaced with `api.mta.info`, which returns the same feed content, but at different URLs and with a different API key parameter (passed as an HTTP header rather than a URL parameter).

### CODE REVIEW

**Comment by Elaniobro** [comment]
@kurtraschke Thank you for generating this PR!

**Comment by ericandrewlewis** [comment]
Thanks for opening the PR.

I had a very rudimentary test in [`test.js`](https://github.com/ericandrewlewis/mta-realtime-subway-departures/blob/master/test.js) that you can run with `npm test`.

The test doesn't work when I check out your branch. I get this error:

```
22:56 $ npm test

> mta-realtime-subway-departures@0.0.13 test /Users/ericlewis/Desktop/mta-realtime-subway-departures
> node test.js

9c53a03b8da895b96df75e8fb6e9ffd5
💁‍♀️ All tests pass.
(node:75133) UnhandledPromiseRejectionWarning: RangeError: Illegal offset: 0 <= 112 (+1) <= 23
    at ByteBuffer.module.exports.ByteBufferPrototype.readVarint32 (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/bytebuffer/dist/bytebuffer-node.js:1540:23)
    at skipTillGroupEnd (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:3177:27)
    at Message.ProtoBuf.Reflect.MessagePrototype.decode (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:3250:36)
    at Function.Message.decode (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:2952:37)
    at /Users/ericlewis/Desktop/mta-realtime-subway-departures/index.js:35:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
(node:75133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:75133) UnhandledPromiseRejectionWarning: RangeError: Illegal offset: 0 <= 112 (+1) <= 23
    at ByteBuffer.module.exports.ByteBufferPrototype.readVarint32 (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/bytebuffer/dist/bytebuffer-node.js:1540:23)
    at skipTillGroupEnd (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:3177:27)
    at Message.ProtoBuf.Reflect.MessagePrototype.decode (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:3250:36)
    at Function.Message.decode (/Users/ericlewis/Desktop/mta-realtime-subway-departures/node_modules/protobufjs/dist/protobuf.js:2952:37)
    at /Users/ericlewis/Desktop/mta-realtime-subway-departures/index.js:35:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
(node:75133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Sorry this test file is not written better. It displays "all tests pass" but the promise-related failures are bonafide failures I believe?

**Comment by kurtraschke** [comment]
To confirm, do you have a valid API key for [api.mta.info](https://api.mta.info/#/landing) set in the `MTA_API_KEY` environment variable when running `test.js`?  I found that the tests ran without incident locally, and I am able to recreate the test failure that you experienced if I unset `MTA_API_KEY`.

**Review by ericandrewlewis — APPROVED** [review]

**Comment by ericandrewlewis** [comment]
Ah I was using my old API key. Signed up with an account and new key. Tests pass. Thanks for this PR! Merging.

**Comment by Elaniobro** [comment]
@ericandrewlewis looking good, did you cut a new release? I assume this will be 1.0.0 since it has a breaking change, new api key and endpoints and is it is Major in Semver notation.

**Comment by ericandrewlewis** [comment]
@Elaniobro In the past I've used `0.x` for packages I'm releasing but hesitant considering a "real module," however after reading npm's suggestions on [semantic versioning](https://docs.npmjs.com/about-semantic-versioning) I think I should just use 1.0.0 as the first version. Bumped up.

**Comment by Elaniobro** [comment]
@ericandrewlewis Rad! I follow https://semver.org/. Thanks for sharing the npm link. 

Please let me know  if you have to publish the NPM module separately, I see the release but `yarn install` is not picking it up yet. I'll try again tomorrow, as it might just take a day for it to propagate.

Thanks again for the kick ass 📦 pkg!

**Comment by ericandrewlewis** [comment]
Published 1.0.0 to npm now.

**Pull request merged**
